# Generated by Django 5.2.1 on 2025-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sucess', 'sucess'), ('failed', 'failed')], default='pending', max_length=20)),
                ('CreatedAt', models.DateTimeField()),
            ],
        ),
    ]
